### ISSUE TITLE
Unable to open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }

### ISSUE THREAD

**Issue by LucasLeeNDS** [AngoraFuzzer/Angora#112]
Hi,
I try to use Angora but I face some problems.

> thread 'main' panicked at 'Unable to open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', fuzzer/src/check_dep.rs:34:35

stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/result.rs:1284:5
   3: angora::check_dep::mmap_file
   4: angora::command::CommandOpt::new
   5: angora::fuzz_main::fuzz_main
   6: fuzzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Can you give me some advice?

**Comment by vincand** [comment]
I had the same problem！！！

**Comment by DataCorrupted** [comment]
From what I see, it is most likely your path to `fast` or `track` is incorrect.

**Comment by vincand** [comment]
got it,thank u !!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AngoraFuzzer/Angora"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 中午12:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AngoraFuzzer/Angora] Unable to open file: Os { code: 2, kind: NotFound, message: "No such file or directory" } (Issue #112)





 
From what I see, it is most likely your path to fast or track is incorrect.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
