### ISSUE TITLE
Question about the edge coverage number.

### ISSUE THREAD

**Issue by gwangmu** [AngoraFuzzer/Angora#59]
I really appreciate this work. The coding style is impressively neat and the fuzzing performance also looks superior to any other fuzzers that I've used until now :)

I have some questions on the numbers in UI, specifically about the edge coverage numbers.

- Is the edge coverage number based on the _gcov_ result, or just the number of the found entries in the map? 
- Does the current UI show the cumulative edge coverage that Angora has actually found until then?
- Is the map density (DENSITY in UI) is about the number of found edges, or about the number of set bits (1's) in the map?

Thanks again! :D

**Comment by spinpx** [comment]
Hi, @gwangmu 

- Is the edge coverage number based on the gcov result, or just the number of the found entries in the map?

The edge coverage is the number of the found entries in the map. We do not count it based on gcov since it will bring other overhead. 

- Does the current UI show the cumulative edge coverage that Angora has actually found until then?

Yes. We count it like AFL.

- Is the map density (DENSITY in UI) is about the number of found edges, or about the number of set bits (1's) in the map?

Like AFL, it is the number of found edges.

**Comment by gwangmu** [comment]
Thanks for replying. It really helped me a lot :)
